#!/usr/bin/env bash
#
# onboard-installer-ci.sh
#
# Idempotently add the installer-test caller workflow to a scottconverse repo
# via a branch + PR. Skips cleanly if the caller already exists.
#
#   ./onboard-installer-ci.sh <repo>          # one repo, e.g. klodock or scottconverse/klodock
#   ./onboard-installer-ci.sh --all           # sweep EVERY scottconverse repo
#   ./onboard-installer-ci.sh --all --dry-run # show what would happen, change nothing
#
# Requires: gh (authenticated). Uses the GitHub Contents/Git APIs (no local git).
#
set -euo pipefail

OWNER="scottconverse"
CI_REPO="installer-ci"                       # central public repo holding the reusable workflow
CALLER_PATH=".github/workflows/installer-test.yml"
BRANCH="ci/add-installer-test"
PR_TITLE="ci: add installer-test caller workflow"
PR_BODY=$'Adds the reusable installer-test caller (uses '"${OWNER}/${CI_REPO}"$').\n\nAuto-generated by onboard-installer-ci.sh.'

DRY_RUN=0

# The exact caller workflow content we install into each repo.
caller_yaml() {
  cat <<YAML
# Calls the central reusable installer-test workflow.
# Managed by ${OWNER}/${CI_REPO}; edit there, not here.
name: installer-test
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  installer-test:
    uses: ${OWNER}/${CI_REPO}/.github/workflows/installer-test.yml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit
YAML
}

log()  { printf '%s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

command -v gh >/dev/null 2>&1 || die "gh CLI not found on PATH"
gh auth status >/dev/null 2>&1 || die "gh is not authenticated (run: gh auth login)"

# Minimal jq passthrough; falls back to python3 if jq is absent.
gh_jq() {
  # $1 = dotted filter like '.isArchived' or '.defaultBranchRef.name'; JSON on stdin.
  if command -v jq >/dev/null 2>&1; then
    jq -r "$1"
  else
    python3 -c 'import sys,json
flt=sys.argv[1].strip().lstrip(".")
cur=json.load(sys.stdin)
if flt:
    for part in flt.split("."):
        cur = (cur or {}).get(part) if isinstance(cur,dict) else None
print("" if cur is None else (str(cur).lower() if isinstance(cur,bool) else cur))' "$1"
  fi
}

# Onboard a single repo. Safe to re-run.
onboard_one() {
  local repo="$1"
  case "$repo" in
    */*) : ;;
    *)   repo="${OWNER}/${repo}" ;;
  esac

  # The central CI repo never calls itself.
  if [ "$repo" = "${OWNER}/${CI_REPO}" ]; then
    log "skip ${repo}: this is the central CI repo"
    return 0
  fi

  # Skip archived repos (cannot push) and resolve default branch.
  local meta default_branch archived
  if ! meta="$(gh repo view "$repo" --json defaultBranchRef,isArchived 2>/dev/null)"; then
    log "skip ${repo}: cannot read repo (missing or no access)"
    return 0
  fi
  archived="$(printf '%s' "$meta" | gh_jq '.isArchived')"
  default_branch="$(printf '%s' "$meta" | gh_jq '.defaultBranchRef.name')"
  [ "$archived" = "true" ] && { log "skip ${repo}: archived"; return 0; }
  { [ -z "$default_branch" ] || [ "$default_branch" = "null" ]; } && { log "skip ${repo}: empty repo (no default branch)"; return 0; }

  # IDEMPOTENCY 1: caller already present on the default branch?
  if gh api "repos/${repo}/contents/${CALLER_PATH}?ref=${default_branch}" >/dev/null 2>&1; then
    log "skip ${repo}: ${CALLER_PATH} already present on ${default_branch}"
    return 0
  fi

  # IDEMPOTENCY 2: an open PR from our branch already exists?
  local existing_pr
  existing_pr="$(gh pr list --repo "$repo" --head "$BRANCH" --state open --json url --jq '.[0].url' 2>/dev/null || true)"
  if [ -n "$existing_pr" ]; then
    log "skip ${repo}: open onboarding PR already exists -> ${existing_pr}"
    return 0
  fi

  if [ "$DRY_RUN" = "1" ]; then
    log "DRY-RUN ${repo}: would create branch '${BRANCH}' off '${default_branch}' and open a PR adding ${CALLER_PATH}"
    return 0
  fi

  # Resolve the default branch head SHA to branch from.
  local base_sha
  base_sha="$(gh api "repos/${repo}/git/ref/heads/${default_branch}" --jq '.object.sha')"

  # Create the branch (ignore "already exists").
  gh api -X POST "repos/${repo}/git/refs" \
    -f ref="refs/heads/${BRANCH}" -f sha="${base_sha}" >/dev/null 2>&1 || true

  # Commit the caller file onto the branch via the Contents API (base64).
  local b64
  b64="$(caller_yaml | base64 | tr -d '\n')"
  gh api -X PUT "repos/${repo}/contents/${CALLER_PATH}" \
    -f message="ci: add installer-test caller workflow" \
    -f content="${b64}" \
    -f branch="${BRANCH}" >/dev/null

  # Open the PR (ignore races).
  local pr_url
  if pr_url="$(gh pr create --repo "$repo" --base "$default_branch" --head "$BRANCH" \
                --title "$PR_TITLE" --body "$PR_BODY" 2>/dev/null)"; then
    log "ok   ${repo}: opened PR -> ${pr_url}"
  else
    pr_url="$(gh pr list --repo "$repo" --head "$BRANCH" --state open --json url --jq '.[0].url' 2>/dev/null || true)"
    log "ok   ${repo}: branch pushed; PR -> ${pr_url:-<create manually>}"
  fi
}

main() {
  local mode="" repo_arg=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --all)     mode="all" ;;
      --dry-run) DRY_RUN=1 ;;
      -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
      -*)        die "unknown flag: $1" ;;
      *)         repo_arg="$1"; mode="${mode:-one}" ;;
    esac
    shift
  done

  case "$mode" in
    one)
      [ -n "$repo_arg" ] || die "usage: $0 <repo> | --all [--dry-run]"
      onboard_one "$repo_arg"
      ;;
    all)
      log "Sweeping all ${OWNER} repos (non-archived)..."
      gh repo list "$OWNER" --no-archived --limit 1000 --json nameWithOwner --jq '.[].nameWithOwner' \
        | while IFS= read -r r; do
            [ -n "$r" ] || continue
            onboard_one "$r" || log "warn ${r}: onboarding step failed (continuing)"
          done
      ;;
    *)
      die "usage: $0 <repo> | --all [--dry-run]"
      ;;
  esac
  log "Done."
}

main "$@"
